# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1558, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidewalk = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.sidewalk.setGeometry(QtCore.QRect(1250, 70, 271, 31))
        self.sidewalk.setObjectName("sidewalk")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1120, 80, 101, 16))
        self.label.setObjectName("label")
        self.newWindow = QtWidgets.QPushButton(self.centralwidget)
        self.newWindow.setGeometry(QtCore.QRect(1120, 450, 101, 31))
        self.newWindow.setObjectName("newWindow")
        self.computeLength = QtWidgets.QPushButton(self.centralwidget)
        self.computeLength.setGeometry(QtCore.QRect(1240, 490, 111, 31))
        self.computeLength.setObjectName("computeLength")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1120, 190, 81, 16))
        self.label_7.setObjectName("label_7")
        self.A = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(1250, 180, 271, 31))
        self.A.setObjectName("A")
        self.viewBtn = QtWidgets.QPushButton(self.centralwidget)
        self.viewBtn.setGeometry(QtCore.QRect(1230, 450, 121, 31))
        self.viewBtn.setObjectName("viewBtn")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(1120, 490, 101, 31))
        self.clear.setObjectName("clear")
        self.velocity = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.velocity.setGeometry(QtCore.QRect(1250, 340, 271, 31))
        self.velocity.setObjectName("velocity")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1120, 350, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1120, 240, 81, 16))
        self.label_8.setObjectName("label_8")
        self.B = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(1250, 230, 271, 31))
        self.B.setObjectName("B")
        self.C = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(1250, 280, 271, 31))
        self.C.setObjectName("C")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1120, 290, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1120, 400, 60, 16))
        self.label_4.setObjectName("label_4")
        self.num_of_order = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.num_of_order.setGeometry(QtCore.QRect(1250, 120, 271, 31))
        self.num_of_order.setObjectName("num_of_order")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1120, 130, 81, 16))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1558, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "增加走道編號"))
        self.newWindow.setText(_translate("MainWindow", "產生訂單"))
        self.computeLength.setText(_translate("MainWindow", "計算路徑"))
        self.label_7.setText(_translate("MainWindow", "A"))
        self.viewBtn.setText(_translate("MainWindow", "View"))
        self.clear.setText(_translate("MainWindow", "清除"))
        self.label_3.setText(_translate("MainWindow", "速度(m/s)"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.label_9.setText(_translate("MainWindow", "C"))
        self.label_4.setText(_translate("MainWindow", "統計："))
        self.label_10.setText(_translate("MainWindow", "訂單數"))
